spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: abc
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console.enabled: true
  config:
    activate:
      on-profile: default